### ISSUE TITLE
invalid Roles are outputted

### ISSUE THREAD

**Issue by vrabbi** [liggitt/audit2rbac#24]
the tool is great but has a bug. it outputs roles and clusterroles with resourceNames even when it includes the create verb which is not possible in K8s.
is this something that can be fixed in the project?
currently i am manually removing the resource names field from those places but it would be much better if the tool did this itself

**Comment by liggitt** [comment]
Thanks for reporting the issue... it's very strange, since I've seen generation of create roles work properly, emitting without `resourceNames` populated (see the example in the demo at https://www.youtube.com/watch?v=n2cD20moYe8&t=137s at 2:17)

At first I thought it might be differences in audit configurations _sometimes_ emitting the resource name in audit events for create requests, but in that same demo, you can see create requests audit events containing object names (e.g. at https://www.youtube.com/watch?v=n2cD20moYe8&t=5s at 0:05), so in *that* configuration, audit events contained names of objects being created, and a create permission was added to the role without populating the name.

I'll take a look to see if I can figure out why this was *sometimes* producing correct create roles, and make the output work consistently.

**Comment by vrabbi** [comment]
would it help if i sent you the audit log?

**Comment by liggitt** [comment]
sure, testdata is always welcome, though the transformation from audit events to authorizer attributes clearly just copies in the objectRef name:

https://github.com/liggitt/audit2rbac/blob/dc2769ad84470df0282ef7e0caa8110f66596159/cmd/audit2rbac/audit2rbac.go#L572-L580

so if the audit log has an objectRef with a name attribute populated, that will drive a simulated authorization check that doesn't match the authorization check that would have been done in reality

**Comment by liggitt** [comment]
Fixed in https://github.com/liggitt/audit2rbac/commit/f55818ac1fc13378e71ef05fa7384692c31ed956 in https://github.com/liggitt/audit2rbac/releases/tag/v0.10.0
